version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"
  db:
    image: orchardup/mysql
    environment:
      MYSQL_USER: java
      MYSQL_PASSWORD: java
      MYSQL_DATABASE: javatest
    ports:
      - "3306"
